import { ReturnRecord, ProductSummary, ReturnPattern } from './types';

export const INITIAL_RETURNS: ReturnRecord[] = [
  {
    id: 'RET-8921',
    orderId: 'ORD-10492',
    customerName: 'Sarah Jenkins',
    customerEmail: 'sarah.j@example.com',
    sku: 'AUDIO-PRO-BLK',
    productName: 'Pro Acoustic Wireless Headphones',
    category: 'Electronics',
    price: 189.99,
    returnDate: '2026-08-28',
    reasonCategory: 'Defect / Hardware',
    customerComment: 'Left earbud stopped charging after 3 days. Battery light stays red.',
    severity: 'High',
    status: 'Analyzed',
    aiAnalysis: {
      reason: 'Hardware Charging Port Defect',
      category: 'Product Quality',
      severity: 'high',
      sentiment: 'negative',
      summary: 'Left earbud stopped charging after 3 days. Battery light stays red.',
      recommendedAction: 'Issue supplier alert to factory QC team; isolate Batch #402 serial numbers.',
      confidence: 0.95,
      identifiedReason: 'Hardware Charging Port Defect',
      rootCause: 'Batch #402 charging terminal pin misalignment on left cup',
      suggestedCategory: 'Defect / Hardware',
      sentimentScore: 0.2,
      analyzedAt: '2026-08-28 14:30',
    },
  },
  {
    id: 'RET-8922',
    orderId: 'ORD-10488',
    customerName: 'Marcus Vance',
    customerEmail: 'm.vance@example.com',
    sku: 'APPAREL-FIT-M',
    productName: 'Ultra-Soft Organic Cotton Hoodie (Medium)',
    category: 'Apparel',
    price: 64.50,
    returnDate: '2026-08-27',
    reasonCategory: 'Sizing Issue',
    customerComment: 'Fabric quality is great, but the Medium fits like a Small. Sleeves are way too short.',
    severity: 'Medium',
    status: 'Analyzed',
    aiAnalysis: {
      reason: 'Inaccurate Size Chart / Undersized Sleeve Cut',
      category: 'Size/Fit',
      severity: 'medium',
      sentiment: 'negative',
      summary: 'Medium fits like a Small. Sleeves are short.',
      recommendedAction: 'Update product page sizing chart with recommendations to size up.',
      confidence: 0.92,
      identifiedReason: 'Inaccurate Size Chart / Undersized Sleeve Cut',
      rootCause: 'Sizing chart on product page does not account for post-wash shrinkage',
      suggestedCategory: 'Sizing Issue',
      sentimentScore: 0.5,
      analyzedAt: '2026-08-27 11:15',
    },
  },
  {
    id: 'RET-8923',
    orderId: 'ORD-10475',
    customerName: 'Elena Rostova',
    customerEmail: 'elena.r@example.com',
    sku: 'HOME-COFFEE-BAR',
    productName: 'Precision Espresso Drip Machine',
    category: 'Home & Kitchen',
    price: 249.00,
    returnDate: '2026-08-26',
    reasonCategory: 'Damaged in Transit',
    customerComment: 'Glass carafe arrived completely shattered inside the box. Outer packaging had heavy denting.',
    severity: 'Critical',
    status: 'Analyzed',
    aiAnalysis: {
      identifiedReason: 'Insufficient Protective Transit Packaging',
      rootCause: 'Single-wall cardboard shipping box lacking internal foam corners',
      suggestedCategory: 'Damaged in Transit',
      sentimentScore: 0.1,
      recommendedAction: 'Mandate double-wall corrugated boxing with molded styrofoam inserts for glass items.',
      analyzedAt: '2026-08-26 16:45',
    },
  },
  {
    id: 'RET-8924',
    orderId: 'ORD-10460',
    customerName: 'David Chen',
    customerEmail: 'dchen@example.com',
    sku: 'AUDIO-PRO-BLK',
    productName: 'Pro Acoustic Wireless Headphones',
    category: 'Electronics',
    price: 189.99,
    returnDate: '2026-08-25',
    reasonCategory: 'Defect / Hardware',
    customerComment: 'Bluetooth keeps dropping connection every 2 minutes when phone is in pocket.',
    severity: 'High',
    status: 'Analyzed',
    aiAnalysis: {
      identifiedReason: 'Bluetooth Firmware Signal Dropout',
      rootCause: 'Firmware v1.2 antenna power throttle in low-power standby mode',
      suggestedCategory: 'Defect / Hardware',
      sentimentScore: 0.3,
      recommendedAction: 'Deploy Bluetooth Firmware patch v1.3 via app or recall affected batch.',
      analyzedAt: '2026-08-25 18:20',
    },
  },
  {
    id: 'RET-8925',
    orderId: 'ORD-10442',
    customerName: 'Jessica Taylor',
    customerEmail: 'jtaylor@example.com',
    sku: 'FIT-TRACKER-V2',
    productName: 'AeroPulse Smart Fitness Band',
    category: 'Electronics',
    price: 89.99,
    returnDate: '2026-08-25',
    reasonCategory: 'Buyer Remorse',
    customerComment: 'Decided to get a higher end smartwatch instead. Item unopened.',
    severity: 'Low',
    status: 'Analyzed',
    aiAnalysis: {
      identifiedReason: 'Standard Buyer Remorse / Upgrade Preference',
      rootCause: 'No product defect detected; customer chose alternative device',
      suggestedCategory: 'Buyer Remorse',
      sentimentScore: 0.8,
      recommendedAction: 'Restock product for immediate resale; no listing or supplier action needed.',
      analyzedAt: '2026-08-25 09:30',
    },
  },
  {
    id: 'RET-8926',
    orderId: 'ORD-10430',
    customerName: 'Brian Miller',
    customerEmail: 'bmiller@example.com',
    sku: 'APPAREL-FIT-M',
    productName: 'Ultra-Soft Organic Cotton Hoodie (Medium)',
    category: 'Apparel',
    price: 64.50,
    returnDate: '2026-08-24',
    reasonCategory: 'Sizing Issue',
    customerComment: 'Too tight around shoulders. Medium fits like a Small.',
    severity: 'Medium',
    status: 'Unanalyzed',
  },
  {
    id: 'RET-8927',
    orderId: 'ORD-10418',
    customerName: 'Amanda Lopez',
    customerEmail: 'alopez@example.com',
    sku: 'HOME-COOK-SET',
    productName: 'Non-Stick Ceramic Cookware Set (10-Piece)',
    category: 'Home & Kitchen',
    price: 179.99,
    returnDate: '2026-08-23',
    reasonCategory: 'Quality Defect',
    customerComment: 'Ceramic coating started peeling after first dishwasher cycle despite hand-wash label.',
    severity: 'High',
    status: 'Unanalyzed',
  },
  {
    id: 'RET-8928',
    orderId: 'ORD-10405',
    customerName: 'Kevin Patel',
    customerEmail: 'kpatel@example.com',
    sku: 'AUDIO-PRO-BLK',
    productName: 'Pro Acoustic Wireless Headphones',
    category: 'Electronics',
    price: 189.99,
    returnDate: '2026-08-22',
    reasonCategory: 'Defect / Hardware',
    customerComment: 'Left headphone speaker has loud crackling sound at high volume.',
    severity: 'High',
    status: 'Unanalyzed',
  }
];

export const INITIAL_PRODUCTS: ProductSummary[] = [
  {
    sku: 'AUDIO-PRO-BLK',
    name: 'Pro Acoustic Wireless Headphones',
    category: 'Electronics',
    price: 189.99,
    totalSold: 420,
    totalReturned: 38,
    returnRate: 9.05,
    severityScore: 8.5,
    topReturnReason: 'Left Cup Hardware & Connectivity Defect',
    riskStatus: 'Critical Issue',
  },
  {
    sku: 'HOME-COFFEE-BAR',
    name: 'Precision Espresso Drip Machine',
    category: 'Home & Kitchen',
    price: 249.00,
    totalSold: 280,
    totalReturned: 21,
    returnRate: 7.50,
    severityScore: 7.8,
    topReturnReason: 'Packaging Transit Damage',
    riskStatus: 'High Risk',
  },
  {
    sku: 'APPAREL-FIT-M',
    name: 'Ultra-Soft Organic Cotton Hoodie (Medium)',
    category: 'Apparel',
    price: 64.50,
    totalSold: 850,
    totalReturned: 52,
    returnRate: 6.11,
    severityScore: 5.2,
    topReturnReason: 'Inaccurate Size Chart / Tight Fit',
    riskStatus: 'Medium Risk',
  },
  {
    sku: 'HOME-COOK-SET',
    name: 'Non-Stick Ceramic Cookware Set (10-Piece)',
    category: 'Home & Kitchen',
    price: 179.99,
    totalSold: 310,
    totalReturned: 14,
    returnRate: 4.51,
    severityScore: 6.0,
    topReturnReason: 'Ceramic Coating Flaking',
    riskStatus: 'Medium Risk',
  },
  {
    sku: 'FIT-TRACKER-V2',
    name: 'AeroPulse Smart Fitness Band',
    category: 'Electronics',
    price: 89.99,
    totalSold: 1200,
    totalReturned: 18,
    returnRate: 1.50,
    severityScore: 2.1,
    topReturnReason: 'Buyer Remorse / Color Swap',
    riskStatus: 'Low Risk',
  },
];

export const INITIAL_PATTERNS: ReturnPattern[] = [
  {
    id: 'PAT-101',
    title: 'Left Cup Power Failure & Disconnect in Wireless Headphones',
    category: 'Electronics',
    affectedSkus: ['AUDIO-PRO-BLK'],
    affectedProductsCount: 1,
    totalReturnCount: 28,
    severity: 'Critical',
    patternDescription: 'Multiple customer reports highlight left earbud charging pin misalignment and Bluetooth dropouts after 2-5 days of use.',
    rootCauseAnalysis: 'Batch #402 component solder batch defect causing voltage imbalance in left transducer module.',
    recommendedActions: [
      'Halt shipment for serial range #402-0000 to #402-1500.',
      'Request supplier quality auditor inspection report from Dongguan plant.',
      'Send proactive email with firmware update instructions to recent buyers.'
    ],
    estimatedCostImpact: 5319.72,
    status: 'Detected',
    detectedDate: '2026-08-28',
  },
  {
    id: 'PAT-102',
    title: 'Systemic Undersizing on Apparel Cotton Hoodies',
    category: 'Apparel',
    affectedSkus: ['APPAREL-FIT-M', 'APPAREL-FIT-L'],
    affectedProductsCount: 2,
    totalReturnCount: 41,
    severity: 'Medium',
    patternDescription: '78% of returns for Medium and Large Hoodies cite sleeve length shrinkage and tight chest measurement.',
    rootCauseAnalysis: 'Pre-shrunk cotton specification was omitted in Q3 production run leading to 4% shrinkage post-wash.',
    recommendedActions: [
      'Update product page size guide advising customers to order 1 size larger.',
      'Revise technical spec pack for next factory production run.'
    ],
    estimatedCostImpact: 2644.50,
    status: 'In Review',
    detectedDate: '2026-08-25',
  },
  {
    id: 'PAT-103',
    title: 'Fragile Packaging Transit Damage for Glass Espresso Machines',
    category: 'Home & Kitchen',
    affectedSkus: ['HOME-COFFEE-BAR'],
    affectedProductsCount: 1,
    totalReturnCount: 19,
    severity: 'High',
    patternDescription: 'Carafe shattering during ground shipping due to single-ply box packaging without corner guards.',
    rootCauseAnalysis: 'Logistics partner switching to standard mailers without fragile item cushion handling.',
    recommendedActions: [
      'Require warehouse to apply heavy bubble wrap overpack prior to courier dispatch.',
      'File shipping damage insurance claim with logistics carrier.'
    ],
    estimatedCostImpact: 4731.00,
    status: 'Detected',
    detectedDate: '2026-08-24',
  }
];
